# Generated by Django 5.0.1 on 2026-03-30 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kort', models.CharField(choices=[('1', '1 Nolu Kort'), ('2', '2 Nolu Kort'), ('3', '3 Nolu Kort'), ('4', '4 Nolu Kort')], max_length=2, verbose_name='Kort')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('saat', models.CharField(choices=[('08:00', '08:00 - 09:00'), ('09:00', '09:00 - 10:00'), ('10:00', '10:00 - 11:00'), ('11:00', '11:00 - 12:00'), ('12:00', '12:00 - 13:00'), ('13:00', '13:00 - 14:00'), ('14:00', '14:00 - 15:00'), ('15:00', '15:00 - 16:00'), ('16:00', '16:00 - 17:00'), ('17:00', '17:00 - 18:00'), ('18:00', '18:00 - 19:00'), ('19:00', '19:00 - 20:00'), ('20:00', '20:00 - 21:00'), ('21:00', '21:00 - 22:00'), ('22:00', '22:00 - 23:00'), ('23:00', '23:00 - 24:00')], max_length=10, verbose_name='Saat')),
                ('kisi_adi', models.CharField(max_length=100, verbose_name='Oyuncu / Öğrenci Adı')),
                ('aciklama', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not (Özel Ders, Kiralama, Bakım vb.)')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('rezerve_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan Hoca')),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
                'unique_together': {('kort', 'tarih', 'saat')},
            },
        ),
    ]
